apiVersion: apps/v1
kind: Deployment
metadata:
  name: zy-workload-app
  namespace: mtx-project-demo
  labels:
    app: zy-workload-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zy-workload-app
  template:
    metadata:
      labels:
        app: zy-workload-app
    spec:
      containers:
        - name: app
          image: rhapsody008/hello-app:latest
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: cluster-config
