apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zy-workload-app
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: kommander-traefik
  tls:
    - hosts:
        - "*.kgsg.com.sg"
      secretName: claims-local-ca-secret
  rules:
  - host: claims.kgsg.com.sg
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zy-workload-app
            port:
              number: 8080
