apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: zy-workload-app

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- tls.yaml

images:
- name: mintplexlabs/anythingllm
  newName: ghcr.io/open-webui/open-webui
  newTag: main
