apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mtx-project-demo

commonLabels:
  app: zy-workload-app

resources:
- deployment.yaml
- service.yaml
- ingress.yaml


images:
- name: rhapsody008/hello-app
  newName: rhapsody008/hello-app
  newTag: sha-c063081
