apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: claims-local-ca
spec:
  isCA: true
  commonName: claims-local-ca
  secretName: claims-local-ca-secret
  dnsNames:
    - "*.kgsg.com.sg"
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io